In [6]:
import pandas as pd
import wget

# Question 1: Get Pandas version
# Getting Pandas version
pd.__version__


'1.5.3'

In [11]:
# Data for analysis
!python -m wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv


Saved under laptops.csv


# Question 2: How many records are in the dataset?

In [54]:
records_num = len(df)
records_num

2160

In [15]:
# Getting the number of records in the data
df = pd.read_csv ('laptops.csv')
df.tail ()

Laptop       Status  Brand  \
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished  Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished  Razer   

      Model                CPU  RAM  Storage Storage type       GPU  Screen  \
2155  Blade      Intel Core i7   16     1000          SSD  RTX 3060    17.3   
2156  Blade      Intel Core i7   16     1000          SSD  RTX 3070    17.3   
2157  Blade      Intel Core i7   32     1000          SSD  RTX 3080    17.3   
2158   Book  Intel Evo Core i7   16     1000          SSD       NaN    13.4   
2159   Book  Intel Evo Core i7   16      256          SSD       NaN    13.4   

     Touch  Final Price  
2155    No      2699.99  
2156    No      2899.99  
2157    No      3399.99  
2158   Yes      1899.99  
2159   Yes      1699.99

# Question 3: How many laptop brands are presented in the dataset?

In [25]:
# The number of unique laptop brands in the dataset
brand_count = df['Brand'].nunique()
print("Number of laptop brands:", brand_count)

# Getting the name of the brands
unique_brands = df['Brand'].unique()
print("Unique laptop brands:", unique_brands)


Number of laptop brands: 27
Unique laptop brands: ['Asus' 'Alurin' 'MSI' 'HP' 'Lenovo' 'Medion' 'Acer' 'Apple' 'Razer'
 'Gigabyte' 'Dell' 'LG' 'Samsung' 'PcCom' 'Microsoft' 'Primux' 'Prixton'
 'Dynabook Toshiba' 'Thomson' 'Denver' 'Deep Gaming' 'Vant' 'Innjoo'
 'Jetwing' 'Millenium' 'Realme' 'Toshiba']


# Question 4: How many columns in the dataset have missing values?

In [29]:
# column_missing_values = df.isnull().sum()
column_missing_values = df.isnull().any().sum()
# Print the result
print("Number of columns with missing values:", column_missing_values)

Number of columns with missing values: 3


# Question 5: What's the maximum final price of Dell notebooks in the dataset?

In [30]:
# Maximum final price of Dell notebooks
max_final_price = df[df['Brand'] == 'Dell']['Final Price'].max()

# Print the result
print("The maximum final price of Dell notebooks:", max_final_price)


The maximum final price of Dell notebooks: 3936.0


# Question 6:
+ Find the median value of Screen column in the dataset.
+ Next, calculate the most frequent value of the same Screen column.
+ Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
+ Now, calculate the median value of Screen once again.


In [37]:
# Question 6a: Calculating the median of Screen column
screen_median = df['Screen'].median()
print("Screen column median value:", screen_median)

# Question 6b: Most frequent value of screen column
most_frequent_value = df['Screen'].mode()[0]
print("Most frequent value of Screen:", most_frequent_value)

# Question 6c: Using the fillna method to use the most_frequent_value to fill the missing values in Screen column.
df['Screen'].fillna(most_frequent_value, inplace=True)


# Question 6d: Calculating the new median for screen
new_median = df['Screen'].median()
print("New median value of Screen:", new_median)

Screen column median value: 15.6
Most frequent value of Screen: 15.6
New median value of Screen: 15.6


# Question 7:
+ Select all the "Innjoo" laptops from the dataset.
+ Select only columns RAM, Storage, Screen.
+ Get the underlying NumPy array. Let's call it X.
+ Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
+ Compute the inverse of XTX.
+ Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
+ Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
+ What's the sum of all the elements of the result?

In [47]:
import numpy as np
# Question 7a: Select all 'Innjoo' laptops
X = df[df['Brand'] == 'Innjoo'].to_numpy()

# Question 7b: Select only columns RAM, Storage, Screen for 'Innjoo' laptops
X = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']].to_numpy()

# Question 7c: Compute matrix-matrix multiplication between the transpose of X and X.
XTX = np.matmul(X.T, X)

# Question 7d: Computing the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

print (XTX)
print (XTX_inv)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]
[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [52]:
# Question 7e: Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Question 7f: Get 'w' by multiplying (XTX_inv*X.T)*y
w = np.matmul(np.matmul(XTX_inv, X.T), y)

# Question 7g: Sum of all elements
w_sum = np.sum(w)

print("The sum of w is:", w_sum)

The sum of w is: 91.29988062995815
